import { Product } from "./product";

export const PRODUCTS: Product[] = [
  {
    productId: 1,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 2,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 3,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 4,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 5,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 6,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 7,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 8,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },
  {
    productId: 9,
    customerId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'For sale: Reiskocher, never used.',
    productImage: '../assets/image/cuchen.jpeg',
    contact: 'jin@rwth-aachen.de',
    dealType: 'sell',
    postDate: 'before 2 days',
  },

]
